export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_ACCOUNTS_ERROR = 'SET_ACCOUNTS_ERROR';

export const SET_WALLET_CREATE = 'SET_WALLET_CREATE';
export const OPEN_WALLET = 'OPEN_WALLET';
export const OPENING_WALLET = 'OPENING_WALLET';
export const OPEN_WALLET_ERROR = 'OPEN_WALLET_ERROR';
export const HAS_WALLET = 'HAS_WALLET';

export const RUNNING_METHOD = 'RUNNING_METHOD';

export const TOASTY_SUCCESS = 'TOASTY_SUCCESS';
export const TOASTY_ERROR = 'TOASTY_ERROR';

export const RESET_WALLET = 'RESET_WALLET';
